export const eventImage : Record<string,any>= {
    '222' : require('@/assets/images/events/222.png'),
    '333' : require('@/assets/images/events/333.png'),
    '333bf' : require('@/assets/images/events/333bf.png'),
    '333fm' : require('@/assets/images/events/333fm.png'),
    '333ft' : require('@/assets/images/events/333ft.png'),
    '333mbf' : require('@/assets/images/events/333mbf.png'),
    '333oh' : require('@/assets/images/events/333.png'),
    '444' : require('@/assets/images/events/444.png'),
    '444bf' : require('@/assets/images/events/444bf.png'),
    '555' : require('@/assets/images/events/555.png'),
    '555bf' : require('@/assets/images/events/555bf.png'),
    '666' : require('@/assets/images/events/666.png'),
    '777' : require('@/assets/images/events/777.png'),
    'clock' : require('@/assets/images/events/clock.png'),
    'magic' : require('@/assets/images/events/magic.png'),
    'minx' : require('@/assets/images/events/minx.png'),
    'mmagic' : require('@/assets/images/events/mmagic.png'),
    'pyram' : require('@/assets/images/events/pyram.png'),
    'skewb' : require('@/assets/images/events/skewb.png'),
    'sq1' : require('@/assets/images/events/sq1.png')
}

 export const eventMap =  new Map([
  ["222", "2x2"],
  ["333", "3x3"],
  ["333oh", "3x3 à une main"],
  ["333bf", "3x3 à l'aveugle"],
  ["333mbf", "3x3 multiple à l'aveugle"],
  ["333fm", "3x3 résolution optimisé"],
  ["333ft", "3x3 avec les pieds (burk)"],
  ["444", "4x4"],
  ["444bf", "4x4 à l'aveugle"],
  ["555", "5x5"],
  ["555bf", "5x5 à l'aveugle"],
  ["666", "6x6"],
  ["777", "7x7"],
  ["pyram", "Pyraminx"],
  ["skewb", "Skewb"],
  ["sq1", "Square-1"],
  ["minx", "Megaminx"],
  ["clock", "Clock"],
  ["magic", "Magic"],
  ["mmagic", "Master Magic"],
  
]);